import pytest

import subprocess
from pyreq2rpm.pyreq2rpm import convert, convert_requirement

def run_rpmbuild(dep):
    e = subprocess.run(['rpmbuild', '--nobuild', '--define',
                        'dep_test {}'.format(dep),
                        'tests/data/dep.spec'],)
    return e.returncode

@pytest.mark.parametrize(('arg', 'expected'), [
    (['foobar', '~=', '2.4.8'], '(foobar >= 2.4.8 with foobar < 2.5)'),
    (['foobar', '~=', '2.4.8.0'], '(foobar >= 2.4.8 with foobar < 2.4.9)'),
    (['foobar', '~=', '2.4.8.1'], '(foobar >= 2.4.8.1 with foobar < 2.4.9)'),
    (['foobar', '~=', '2.4.8.*'], 'Invalid version'),
    (['foobar', '~=', '2.0'], '(foobar >= 2 with foobar < 3)'),
    (['foobar', '~=', '2'], 'Invalid version'),
    (['foobar', '~=', '2.*'], 'Invalid version'),
    (['foobar', '~=', '2.4.8b5'], '(foobar >= 2.4.8~b5 with foobar < 2.5)'),
    (['foobar', '~=', '2.0.0b5'], '(foobar >= 2~b5 with foobar < 2.1)'),
    (['foobar', '~=', '2.4.8.post1'], '(foobar >= 2.4.8^post1 with foobar < 2.5)'),
    (['foobar', '~=', '2.0.post1'], '(foobar >= 2^post1 with foobar < 3)'),
    (['foobar', '~=', '0.0'], '(foobar >= 0 with foobar < 1)'),
    (['foobar', '==', '2.4.8'], 'foobar = 2.4.8'),
    (['foobar', '==', '2.4.8.0'], 'foobar = 2.4.8'),
    (['foobar', '==', '2.4.8.1'], 'foobar = 2.4.8.1'),
    (['foobar', '==', '2.4.8.*'], '(foobar >= 2.4.8 with foobar < 2.4.9)'),
    (['foobar', '==', '2.0'], 'foobar = 2'),
    (['foobar', '==', '2'], 'foobar = 2'),
    (['foobar', '==', '2.*'], '(foobar >= 2 with foobar < 3)'),
    (['foobar', '==', '2.4.8b5'], 'foobar = 2.4.8~b5'),
    (['foobar', '==', '2.0.0b5'], 'foobar = 2~b5'),
    (['foobar', '==', '2.4.8.post1'], 'foobar = 2.4.8^post1'),
    (['foobar', '==', '2.0.post1'], 'foobar = 2^post1'),
    (['foobar', '==', '0.0'], 'foobar = 0'),
    (['foobar', '===', '2.4.8'], 'foobar = 2.4.8'),
    (['foobar', '===', '2.4.8.0'], 'foobar = 2.4.8'),
    (['foobar', '===', '2.4.8.1'], 'foobar = 2.4.8.1'),
    (['foobar', '===', '2.4.8.*'], 'Invalid version'),
    (['foobar', '===', '2.0'], 'foobar = 2'),
    (['foobar', '===', '2'], 'foobar = 2'),
    (['foobar', '===', '2.*'], 'Invalid version'),
    (['foobar', '===', '2.4.8b5'], 'foobar = 2.4.8~b5'),
    (['foobar', '===', '2.0.0b5'], 'foobar = 2~b5'),
    (['foobar', '===', '2.4.8.post1'], 'foobar = 2.4.8^post1'),
    (['foobar', '===', '2.0.post1'], 'foobar = 2^post1'),
    (['foobar', '===', '0.0'], 'foobar = 0'),
    (['foobar', '!=', '2.4.8'], '(foobar < 2.4.8 or foobar > 2.4.8)'),
    (['foobar', '!=', '2.4.8.0'], '(foobar < 2.4.8 or foobar > 2.4.8)'),
    (['foobar', '!=', '2.4.8.1'], '(foobar < 2.4.8.1 or foobar > 2.4.8.1)'),
    (['foobar', '!=', '2.4.8.*'], '(foobar < 2.4.8~~ or foobar >= 2.4.9)'),
    (['foobar', '!=', '2.0'], '(foobar < 2 or foobar > 2)'),
    (['foobar', '!=', '2'], '(foobar < 2 or foobar > 2)'),
    (['foobar', '!=', '2.*'], '(foobar < 2~~ or foobar >= 3)'),
    (['foobar', '!=', '2.4.8b5'], '(foobar < 2.4.8~b5 or foobar > 2.4.8~b5)'),
    (['foobar', '!=', '2.0.0b5'], '(foobar < 2~b5 or foobar > 2~b5)'),
    (['foobar', '!=', '2.4.8.post1'], '(foobar < 2.4.8^post1 or foobar > 2.4.8^post1)'),
    (['foobar', '!=', '2.0.post1'], '(foobar < 2^post1 or foobar > 2^post1)'),
    (['foobar', '!=', '0.0'], '(foobar < 0 or foobar > 0)'),
    (['foobar', '<=', '2.4.8'], 'foobar <= 2.4.8'),
    (['foobar', '<=', '2.4.8.0'], 'foobar <= 2.4.8'),
    (['foobar', '<=', '2.4.8.1'], 'foobar <= 2.4.8.1'),
    (['foobar', '<=', '2.4.8.*'], 'foobar < 2.4.8~~'), # see notes in pyreq2rpm.convert_ordered
    (['foobar', '<=', '2.0'], 'foobar <= 2'),
    (['foobar', '<=', '2'], 'foobar <= 2'),
    (['foobar', '<=', '2.*'], 'foobar < 2~~'), # see notes in pyreq2rpm.convert_ordered
    (['foobar', '<=', '2.4.8b5'], 'foobar <= 2.4.8~b5'),
    (['foobar', '<=', '2.0.0b5'], 'foobar <= 2~b5'),
    (['foobar', '<=', '2.4.8.post1'], 'foobar <= 2.4.8^post1'),
    (['foobar', '<=', '2.0.post1'], 'foobar <= 2^post1'),
    (['foobar', '<=', '0.0'], 'foobar <= 0'),
    (['foobar', '<', '2.4.8'], 'foobar < 2.4.8~~'),
    (['foobar', '<', '2.4.8.0'], 'foobar < 2.4.8~~'),
    (['foobar', '<', '2.4.8.1'], 'foobar < 2.4.8.1~~'),
    (['foobar', '<', '2.4.8.*'], 'foobar < 2.4.8~~'),
    (['foobar', '<', '2.0'], 'foobar < 2~~'),
    (['foobar', '<', '2'], 'foobar < 2~~'),
    (['foobar', '<', '2.*'], 'foobar < 2~~'),
    (['foobar', '<', '2.4.8b5'], 'foobar < 2.4.8~b5'),
    (['foobar', '<', '2.0.0b5'], 'foobar < 2~b5'),
    (['foobar', '<', '2.4.8.post1'], 'foobar < 2.4.8^post1'),
    (['foobar', '<', '2.0.post1'], 'foobar < 2^post1'),
    (['foobar', '<', '0.0'], 'foobar < 0~~'),
    (['foobar', '>=', '2.4.8'], 'foobar >= 2.4.8'),
    (['foobar', '>=', '2.4.8.0'], 'foobar >= 2.4.8'),
    (['foobar', '>=', '2.4.8.1'], 'foobar >= 2.4.8.1'),
    (['foobar', '>=', '2.4.8.*'], 'foobar >= 2.4.8'),
    (['foobar', '>=', '2.0'], 'foobar >= 2'),
    (['foobar', '>=', '2'], 'foobar >= 2'),
    (['foobar', '>=', '2.*'], 'foobar >= 2'),
    (['foobar', '>=', '2.4.8b5'], 'foobar >= 2.4.8~b5'),
    (['foobar', '>=', '2.0.0b5'], 'foobar >= 2~b5'),
    (['foobar', '>=', '2.4.8.post1'], 'foobar >= 2.4.8^post1'),
    (['foobar', '>=', '2.0.post1'], 'foobar >= 2^post1'),
    (['foobar', '>=', '0.0'], 'foobar >= 0'),
    (['foobar', '>', '2.4.8'], 'foobar > 2.4.8.0'),
    (['foobar', '>', '2.4.8.0'], 'foobar > 2.4.8.0'),
    (['foobar', '>', '2.4.8.1'], 'foobar > 2.4.8.1.0'),
    (['foobar', '>', '2.4.8.*'], 'foobar >= 2.4.8'), # see notes in pyreq2rpm.convert_ordered
    (['foobar', '>', '2.0'], 'foobar > 2.0'),
    (['foobar', '>', '2'], 'foobar > 2.0'),
    (['foobar', '>', '2.*'], 'foobar >= 2'), # see notes in pyreq2rpm.convert_ordered
    (['foobar', '>', '2.4.8b5'], 'foobar > 2.4.8~b5'),
    (['foobar', '>', '2.0.0b5'], 'foobar > 2~b5'),
    (['foobar', '>', '2.4.8.post1'], 'foobar > 2.4.8^post1'),
    (['foobar', '>', '2.0.post1'], 'foobar > 2^post1'),
    (['foobar', '>', '0.0'], 'foobar > 0.0'),
    (['foobar', '>', '1.0.0.dev4'], 'foobar > 1~~dev4'),
    (['foobar', '>', '1.1.1a2'], 'foobar > 1.1.1~a2'),
    (['foobar', '>', '1.1.0rc3'], 'foobar > 1.1~rc3'),
    (['foobar', '~=', '1.0.a1'], '(foobar >= 1~a1 with foobar < 2)'),
    (['foobar', '~=', '1.0.a'], '(foobar >= 1~a0 with foobar < 2)'),
    (['foobar', '~=', '1.0-a1'], '(foobar >= 1~a1 with foobar < 2)'),
    (['foobar', '~=', '1.0-a'], '(foobar >= 1~a0 with foobar < 2)'),
    (['foobar', '~=', '1.0_a1'], '(foobar >= 1~a1 with foobar < 2)'),
    (['foobar', '~=', '1.0_a'], '(foobar >= 1~a0 with foobar < 2)'),
    (['foobar', '~=', '1.0.b1'], '(foobar >= 1~b1 with foobar < 2)'),
    (['foobar', '~=', '1.0.b'], '(foobar >= 1~b0 with foobar < 2)'),
    (['foobar', '~=', '1.0-b1'], '(foobar >= 1~b1 with foobar < 2)'),
    (['foobar', '~=', '1.0-b'], '(foobar >= 1~b0 with foobar < 2)'),
    (['foobar', '~=', '1.0_b1'], '(foobar >= 1~b1 with foobar < 2)'),
    (['foobar', '~=', '1.0_b'], '(foobar >= 1~b0 with foobar < 2)'),
    (['foobar', '~=', '1.0.rc1'], '(foobar >= 1~rc1 with foobar < 2)'),
    (['foobar', '~=', '1.0.rc'], '(foobar >= 1~rc0 with foobar < 2)'),
    (['foobar', '~=', '1.0-rc1'], '(foobar >= 1~rc1 with foobar < 2)'),
    (['foobar', '~=', '1.0-rc'], '(foobar >= 1~rc0 with foobar < 2)'),
    (['foobar', '~=', '1.0_rc1'], '(foobar >= 1~rc1 with foobar < 2)'),
    (['foobar', '~=', '1.0_rc'], '(foobar >= 1~rc0 with foobar < 2)'),
    (['foobar', '~=', '1.0.alpha1'], '(foobar >= 1~a1 with foobar < 2)'),
    (['foobar', '~=', '1.0.alpha'], '(foobar >= 1~a0 with foobar < 2)'),
    (['foobar', '~=', '1.0-alpha1'], '(foobar >= 1~a1 with foobar < 2)'),
    (['foobar', '~=', '1.0-alpha'], '(foobar >= 1~a0 with foobar < 2)'),
    (['foobar', '~=', '1.0_alpha1'], '(foobar >= 1~a1 with foobar < 2)'),
    (['foobar', '~=', '1.0_alpha'], '(foobar >= 1~a0 with foobar < 2)'),
    (['foobar', '~=', '1.0.beta1'], '(foobar >= 1~b1 with foobar < 2)'),
    (['foobar', '~=', '1.0.beta'], '(foobar >= 1~b0 with foobar < 2)'),
    (['foobar', '~=', '1.0-beta1'], '(foobar >= 1~b1 with foobar < 2)'),
    (['foobar', '~=', '1.0-beta'], '(foobar >= 1~b0 with foobar < 2)'),
    (['foobar', '~=', '1.0_beta1'], '(foobar >= 1~b1 with foobar < 2)'),
    (['foobar', '~=', '1.0_beta'], '(foobar >= 1~b0 with foobar < 2)'),
    (['foobar', '~=', '1.0.c1'], '(foobar >= 1~rc1 with foobar < 2)'),
    (['foobar', '~=', '1.0.c'], '(foobar >= 1~rc0 with foobar < 2)'),
    (['foobar', '~=', '1.0-c1'], '(foobar >= 1~rc1 with foobar < 2)'),
    (['foobar', '~=', '1.0-c'], '(foobar >= 1~rc0 with foobar < 2)'),
    (['foobar', '~=', '1.0_c1'], '(foobar >= 1~rc1 with foobar < 2)'),
    (['foobar', '~=', '1.0_c'], '(foobar >= 1~rc0 with foobar < 2)'),
    (['foobar', '~=', '1.0.pre1'], '(foobar >= 1~rc1 with foobar < 2)'),
    (['foobar', '~=', '1.0.pre'], '(foobar >= 1~rc0 with foobar < 2)'),
    (['foobar', '~=', '1.0-pre1'], '(foobar >= 1~rc1 with foobar < 2)'),
    (['foobar', '~=', '1.0-pre'], '(foobar >= 1~rc0 with foobar < 2)'),
    (['foobar', '~=', '1.0_pre1'], '(foobar >= 1~rc1 with foobar < 2)'),
    (['foobar', '~=', '1.0_pre'], '(foobar >= 1~rc0 with foobar < 2)'),
    (['foobar', '~=', '1.0.preview1'], '(foobar >= 1~rc1 with foobar < 2)'),
    (['foobar', '~=', '1.0.preview'], '(foobar >= 1~rc0 with foobar < 2)'),
    (['foobar', '~=', '1.0-preview1'], '(foobar >= 1~rc1 with foobar < 2)'),
    (['foobar', '~=', '1.0-preview'], '(foobar >= 1~rc0 with foobar < 2)'),
    (['foobar', '~=', '1.0_preview1'], '(foobar >= 1~rc1 with foobar < 2)'),
    (['foobar', '~=', '1.0_preview'], '(foobar >= 1~rc0 with foobar < 2)'),
    (['foobar', '~=', '1.0post1'], '(foobar >= 1^post1 with foobar < 2)'),
    (['foobar', '~=', '1.0post'], '(foobar >= 1^post0 with foobar < 2)'),
    (['foobar', '~=', '1.0.post1'], '(foobar >= 1^post1 with foobar < 2)'),
    (['foobar', '~=', '1.0.post'], '(foobar >= 1^post0 with foobar < 2)'),
    (['foobar', '~=', '1.0-post1'], '(foobar >= 1^post1 with foobar < 2)'),
    (['foobar', '~=', '1.0-post'], '(foobar >= 1^post0 with foobar < 2)'),
    (['foobar', '~=', '1.0_post1'], '(foobar >= 1^post1 with foobar < 2)'),
    (['foobar', '~=', '1.0_post'], '(foobar >= 1^post0 with foobar < 2)'),
    (['foobar', '~=', '1.0rev1'], '(foobar >= 1^post1 with foobar < 2)'),
    (['foobar', '~=', '1.0rev'], '(foobar >= 1^post0 with foobar < 2)'),
    (['foobar', '~=', '1.0.rev1'], '(foobar >= 1^post1 with foobar < 2)'),
    (['foobar', '~=', '1.0.rev'], '(foobar >= 1^post0 with foobar < 2)'),
    (['foobar', '~=', '1.0-rev1'], '(foobar >= 1^post1 with foobar < 2)'),
    (['foobar', '~=', '1.0-rev'], '(foobar >= 1^post0 with foobar < 2)'),
    (['foobar', '~=', '1.0_rev1'], '(foobar >= 1^post1 with foobar < 2)'),
    (['foobar', '~=', '1.0_rev'], '(foobar >= 1^post0 with foobar < 2)'),
    (['foobar', '~=', '1.0r1'], '(foobar >= 1^post1 with foobar < 2)'),
    (['foobar', '~=', '1.0r'], '(foobar >= 1^post0 with foobar < 2)'),
    (['foobar', '~=', '1.0.r1'], '(foobar >= 1^post1 with foobar < 2)'),
    (['foobar', '~=', '1.0.r'], '(foobar >= 1^post0 with foobar < 2)'),
    (['foobar', '~=', '1.0-r1'], '(foobar >= 1^post1 with foobar < 2)'),
    (['foobar', '~=', '1.0-r'], '(foobar >= 1^post0 with foobar < 2)'),
    (['foobar', '~=', '1.0_r1'], '(foobar >= 1^post1 with foobar < 2)'),
    (['foobar', '~=', '1.0_r'], '(foobar >= 1^post0 with foobar < 2)'),
    (['foobar', '~=', '1.0-1'], '(foobar >= 1^post1 with foobar < 2)'),
    (['foobar', '==', '1.0.a1'], 'foobar = 1~a1'),
    (['foobar', '==', '1.0.a'], 'foobar = 1~a0'),
    (['foobar', '==', '1.0-a1'], 'foobar = 1~a1'),
    (['foobar', '==', '1.0-a'], 'foobar = 1~a0'),
    (['foobar', '==', '1.0_a1'], 'foobar = 1~a1'),
    (['foobar', '==', '1.0_a'], 'foobar = 1~a0'),
    (['foobar', '==', '1.0.b1'], 'foobar = 1~b1'),
    (['foobar', '==', '1.0.b'], 'foobar = 1~b0'),
    (['foobar', '==', '1.0-b1'], 'foobar = 1~b1'),
    (['foobar', '==', '1.0-b'], 'foobar = 1~b0'),
    (['foobar', '==', '1.0_b1'], 'foobar = 1~b1'),
    (['foobar', '==', '1.0_b'], 'foobar = 1~b0'),
    (['foobar', '==', '1.0.rc1'], 'foobar = 1~rc1'),
    (['foobar', '==', '1.0.rc'], 'foobar = 1~rc0'),
    (['foobar', '==', '1.0-rc1'], 'foobar = 1~rc1'),
    (['foobar', '==', '1.0-rc'], 'foobar = 1~rc0'),
    (['foobar', '==', '1.0_rc1'], 'foobar = 1~rc1'),
    (['foobar', '==', '1.0_rc'], 'foobar = 1~rc0'),
    (['foobar', '==', '1.0.alpha1'], 'foobar = 1~a1'),
    (['foobar', '==', '1.0.alpha'], 'foobar = 1~a0'),
    (['foobar', '==', '1.0-alpha1'], 'foobar = 1~a1'),
    (['foobar', '==', '1.0-alpha'], 'foobar = 1~a0'),
    (['foobar', '==', '1.0_alpha1'], 'foobar = 1~a1'),
    (['foobar', '==', '1.0_alpha'], 'foobar = 1~a0'),
    (['foobar', '==', '1.0.beta1'], 'foobar = 1~b1'),
    (['foobar', '==', '1.0.beta'], 'foobar = 1~b0'),
    (['foobar', '==', '1.0-beta1'], 'foobar = 1~b1'),
    (['foobar', '==', '1.0-beta'], 'foobar = 1~b0'),
    (['foobar', '==', '1.0_beta1'], 'foobar = 1~b1'),
    (['foobar', '==', '1.0_beta'], 'foobar = 1~b0'),
    (['foobar', '==', '1.0.c1'], 'foobar = 1~rc1'),
    (['foobar', '==', '1.0.c'], 'foobar = 1~rc0'),
    (['foobar', '==', '1.0-c1'], 'foobar = 1~rc1'),
    (['foobar', '==', '1.0-c'], 'foobar = 1~rc0'),
    (['foobar', '==', '1.0_c1'], 'foobar = 1~rc1'),
    (['foobar', '==', '1.0_c'], 'foobar = 1~rc0'),
    (['foobar', '==', '1.0.pre1'], 'foobar = 1~rc1'),
    (['foobar', '==', '1.0.pre'], 'foobar = 1~rc0'),
    (['foobar', '==', '1.0-pre1'], 'foobar = 1~rc1'),
    (['foobar', '==', '1.0-pre'], 'foobar = 1~rc0'),
    (['foobar', '==', '1.0_pre1'], 'foobar = 1~rc1'),
    (['foobar', '==', '1.0_pre'], 'foobar = 1~rc0'),
    (['foobar', '==', '1.0.preview1'], 'foobar = 1~rc1'),
    (['foobar', '==', '1.0.preview'], 'foobar = 1~rc0'),
    (['foobar', '==', '1.0-preview1'], 'foobar = 1~rc1'),
    (['foobar', '==', '1.0-preview'], 'foobar = 1~rc0'),
    (['foobar', '==', '1.0_preview1'], 'foobar = 1~rc1'),
    (['foobar', '==', '1.0_preview'], 'foobar = 1~rc0'),
    (['foobar', '==', '1.0post1'], 'foobar = 1^post1'),
    (['foobar', '==', '1.0post'], 'foobar = 1^post0'),
    (['foobar', '==', '1.0.post1'], 'foobar = 1^post1'),
    (['foobar', '==', '1.0.post'], 'foobar = 1^post0'),
    (['foobar', '==', '1.0-post1'], 'foobar = 1^post1'),
    (['foobar', '==', '1.0-post'], 'foobar = 1^post0'),
    (['foobar', '==', '1.0_post1'], 'foobar = 1^post1'),
    (['foobar', '==', '1.0_post'], 'foobar = 1^post0'),
    (['foobar', '==', '1.0rev1'], 'foobar = 1^post1'),
    (['foobar', '==', '1.0rev'], 'foobar = 1^post0'),
    (['foobar', '==', '1.0.rev1'], 'foobar = 1^post1'),
    (['foobar', '==', '1.0.rev'], 'foobar = 1^post0'),
    (['foobar', '==', '1.0-rev1'], 'foobar = 1^post1'),
    (['foobar', '==', '1.0-rev'], 'foobar = 1^post0'),
    (['foobar', '==', '1.0_rev1'], 'foobar = 1^post1'),
    (['foobar', '==', '1.0_rev'], 'foobar = 1^post0'),
    (['foobar', '==', '1.0r1'], 'foobar = 1^post1'),
    (['foobar', '==', '1.0r'], 'foobar = 1^post0'),
    (['foobar', '==', '1.0.r1'], 'foobar = 1^post1'),
    (['foobar', '==', '1.0.r'], 'foobar = 1^post0'),
    (['foobar', '==', '1.0-r1'], 'foobar = 1^post1'),
    (['foobar', '==', '1.0-r'], 'foobar = 1^post0'),
    (['foobar', '==', '1.0_r1'], 'foobar = 1^post1'),
    (['foobar', '==', '1.0_r'], 'foobar = 1^post0'),
    (['foobar', '==', '1.0-1'], 'foobar = 1^post1'),
    (['foobar', '===', '1.0.a1'], 'foobar = 1~a1'),
    (['foobar', '===', '1.0.a'], 'foobar = 1~a0'),
    (['foobar', '===', '1.0-a1'], 'foobar = 1~a1'),
    (['foobar', '===', '1.0-a'], 'foobar = 1~a0'),
    (['foobar', '===', '1.0_a1'], 'foobar = 1~a1'),
    (['foobar', '===', '1.0_a'], 'foobar = 1~a0'),
    (['foobar', '===', '1.0.b1'], 'foobar = 1~b1'),
    (['foobar', '===', '1.0.b'], 'foobar = 1~b0'),
    (['foobar', '===', '1.0-b1'], 'foobar = 1~b1'),
    (['foobar', '===', '1.0-b'], 'foobar = 1~b0'),
    (['foobar', '===', '1.0_b1'], 'foobar = 1~b1'),
    (['foobar', '===', '1.0_b'], 'foobar = 1~b0'),
    (['foobar', '===', '1.0.rc1'], 'foobar = 1~rc1'),
    (['foobar', '===', '1.0.rc'], 'foobar = 1~rc0'),
    (['foobar', '===', '1.0-rc1'], 'foobar = 1~rc1'),
    (['foobar', '===', '1.0-rc'], 'foobar = 1~rc0'),
    (['foobar', '===', '1.0_rc1'], 'foobar = 1~rc1'),
    (['foobar', '===', '1.0_rc'], 'foobar = 1~rc0'),
    (['foobar', '===', '1.0.alpha1'], 'foobar = 1~a1'),
    (['foobar', '===', '1.0.alpha'], 'foobar = 1~a0'),
    (['foobar', '===', '1.0-alpha1'], 'foobar = 1~a1'),
    (['foobar', '===', '1.0-alpha'], 'foobar = 1~a0'),
    (['foobar', '===', '1.0_alpha1'], 'foobar = 1~a1'),
    (['foobar', '===', '1.0_alpha'], 'foobar = 1~a0'),
    (['foobar', '===', '1.0.beta1'], 'foobar = 1~b1'),
    (['foobar', '===', '1.0.beta'], 'foobar = 1~b0'),
    (['foobar', '===', '1.0-beta1'], 'foobar = 1~b1'),
    (['foobar', '===', '1.0-beta'], 'foobar = 1~b0'),
    (['foobar', '===', '1.0_beta1'], 'foobar = 1~b1'),
    (['foobar', '===', '1.0_beta'], 'foobar = 1~b0'),
    (['foobar', '===', '1.0.c1'], 'foobar = 1~rc1'),
    (['foobar', '===', '1.0.c'], 'foobar = 1~rc0'),
    (['foobar', '===', '1.0-c1'], 'foobar = 1~rc1'),
    (['foobar', '===', '1.0-c'], 'foobar = 1~rc0'),
    (['foobar', '===', '1.0_c1'], 'foobar = 1~rc1'),
    (['foobar', '===', '1.0_c'], 'foobar = 1~rc0'),
    (['foobar', '===', '1.0.pre1'], 'foobar = 1~rc1'),
    (['foobar', '===', '1.0.pre'], 'foobar = 1~rc0'),
    (['foobar', '===', '1.0-pre1'], 'foobar = 1~rc1'),
    (['foobar', '===', '1.0-pre'], 'foobar = 1~rc0'),
    (['foobar', '===', '1.0_pre1'], 'foobar = 1~rc1'),
    (['foobar', '===', '1.0_pre'], 'foobar = 1~rc0'),
    (['foobar', '===', '1.0.preview1'], 'foobar = 1~rc1'),
    (['foobar', '===', '1.0.preview'], 'foobar = 1~rc0'),
    (['foobar', '===', '1.0-preview1'], 'foobar = 1~rc1'),
    (['foobar', '===', '1.0-preview'], 'foobar = 1~rc0'),
    (['foobar', '===', '1.0_preview1'], 'foobar = 1~rc1'),
    (['foobar', '===', '1.0_preview'], 'foobar = 1~rc0'),
    (['foobar', '===', '1.0post1'], 'foobar = 1^post1'),
    (['foobar', '===', '1.0post'], 'foobar = 1^post0'),
    (['foobar', '===', '1.0.post1'], 'foobar = 1^post1'),
    (['foobar', '===', '1.0.post'], 'foobar = 1^post0'),
    (['foobar', '===', '1.0-post1'], 'foobar = 1^post1'),
    (['foobar', '===', '1.0-post'], 'foobar = 1^post0'),
    (['foobar', '===', '1.0_post1'], 'foobar = 1^post1'),
    (['foobar', '===', '1.0_post'], 'foobar = 1^post0'),
    (['foobar', '===', '1.0rev1'], 'foobar = 1^post1'),
    (['foobar', '===', '1.0rev'], 'foobar = 1^post0'),
    (['foobar', '===', '1.0.rev1'], 'foobar = 1^post1'),
    (['foobar', '===', '1.0.rev'], 'foobar = 1^post0'),
    (['foobar', '===', '1.0-rev1'], 'foobar = 1^post1'),
    (['foobar', '===', '1.0-rev'], 'foobar = 1^post0'),
    (['foobar', '===', '1.0_rev1'], 'foobar = 1^post1'),
    (['foobar', '===', '1.0_rev'], 'foobar = 1^post0'),
    (['foobar', '===', '1.0r1'], 'foobar = 1^post1'),
    (['foobar', '===', '1.0r'], 'foobar = 1^post0'),
    (['foobar', '===', '1.0.r1'], 'foobar = 1^post1'),
    (['foobar', '===', '1.0.r'], 'foobar = 1^post0'),
    (['foobar', '===', '1.0-r1'], 'foobar = 1^post1'),
    (['foobar', '===', '1.0-r'], 'foobar = 1^post0'),
    (['foobar', '===', '1.0_r1'], 'foobar = 1^post1'),
    (['foobar', '===', '1.0_r'], 'foobar = 1^post0'),
    (['foobar', '===', '1.0-1'], 'foobar = 1^post1'),
    (['foobar', '!=', '1.0.a1'], '(foobar < 1~a1 or foobar > 1~a1)'),
    (['foobar', '!=', '1.0.a'], '(foobar < 1~a0 or foobar > 1~a0)'),
    (['foobar', '!=', '1.0-a1'], '(foobar < 1~a1 or foobar > 1~a1)'),
    (['foobar', '!=', '1.0-a'], '(foobar < 1~a0 or foobar > 1~a0)'),
    (['foobar', '!=', '1.0_a1'], '(foobar < 1~a1 or foobar > 1~a1)'),
    (['foobar', '!=', '1.0_a'], '(foobar < 1~a0 or foobar > 1~a0)'),
    (['foobar', '!=', '1.0.b1'], '(foobar < 1~b1 or foobar > 1~b1)'),
    (['foobar', '!=', '1.0.b'], '(foobar < 1~b0 or foobar > 1~b0)'),
    (['foobar', '!=', '1.0-b1'], '(foobar < 1~b1 or foobar > 1~b1)'),
    (['foobar', '!=', '1.0-b'], '(foobar < 1~b0 or foobar > 1~b0)'),
    (['foobar', '!=', '1.0_b1'], '(foobar < 1~b1 or foobar > 1~b1)'),
    (['foobar', '!=', '1.0_b'], '(foobar < 1~b0 or foobar > 1~b0)'),
    (['foobar', '!=', '1.0.rc1'], '(foobar < 1~rc1 or foobar > 1~rc1)'),
    (['foobar', '!=', '1.0.rc'], '(foobar < 1~rc0 or foobar > 1~rc0)'),
    (['foobar', '!=', '1.0-rc1'], '(foobar < 1~rc1 or foobar > 1~rc1)'),
    (['foobar', '!=', '1.0-rc'], '(foobar < 1~rc0 or foobar > 1~rc0)'),
    (['foobar', '!=', '1.0_rc1'], '(foobar < 1~rc1 or foobar > 1~rc1)'),
    (['foobar', '!=', '1.0_rc'], '(foobar < 1~rc0 or foobar > 1~rc0)'),
    (['foobar', '!=', '1.0.alpha1'], '(foobar < 1~a1 or foobar > 1~a1)'),
    (['foobar', '!=', '1.0.alpha'], '(foobar < 1~a0 or foobar > 1~a0)'),
    (['foobar', '!=', '1.0-alpha1'], '(foobar < 1~a1 or foobar > 1~a1)'),
    (['foobar', '!=', '1.0-alpha'], '(foobar < 1~a0 or foobar > 1~a0)'),
    (['foobar', '!=', '1.0_alpha1'], '(foobar < 1~a1 or foobar > 1~a1)'),
    (['foobar', '!=', '1.0_alpha'], '(foobar < 1~a0 or foobar > 1~a0)'),
    (['foobar', '!=', '1.0.beta1'], '(foobar < 1~b1 or foobar > 1~b1)'),
    (['foobar', '!=', '1.0.beta'], '(foobar < 1~b0 or foobar > 1~b0)'),
    (['foobar', '!=', '1.0-beta1'], '(foobar < 1~b1 or foobar > 1~b1)'),
    (['foobar', '!=', '1.0-beta'], '(foobar < 1~b0 or foobar > 1~b0)'),
    (['foobar', '!=', '1.0_beta1'], '(foobar < 1~b1 or foobar > 1~b1)'),
    (['foobar', '!=', '1.0_beta'], '(foobar < 1~b0 or foobar > 1~b0)'),
    (['foobar', '!=', '1.0.c1'], '(foobar < 1~rc1 or foobar > 1~rc1)'),
    (['foobar', '!=', '1.0.c'], '(foobar < 1~rc0 or foobar > 1~rc0)'),
    (['foobar', '!=', '1.0-c1'], '(foobar < 1~rc1 or foobar > 1~rc1)'),
    (['foobar', '!=', '1.0-c'], '(foobar < 1~rc0 or foobar > 1~rc0)'),
    (['foobar', '!=', '1.0_c1'], '(foobar < 1~rc1 or foobar > 1~rc1)'),
    (['foobar', '!=', '1.0_c'], '(foobar < 1~rc0 or foobar > 1~rc0)'),
    (['foobar', '!=', '1.0.pre1'], '(foobar < 1~rc1 or foobar > 1~rc1)'),
    (['foobar', '!=', '1.0.pre'], '(foobar < 1~rc0 or foobar > 1~rc0)'),
    (['foobar', '!=', '1.0-pre1'], '(foobar < 1~rc1 or foobar > 1~rc1)'),
    (['foobar', '!=', '1.0-pre'], '(foobar < 1~rc0 or foobar > 1~rc0)'),
    (['foobar', '!=', '1.0_pre1'], '(foobar < 1~rc1 or foobar > 1~rc1)'),
    (['foobar', '!=', '1.0_pre'], '(foobar < 1~rc0 or foobar > 1~rc0)'),
    (['foobar', '!=', '1.0.preview1'], '(foobar < 1~rc1 or foobar > 1~rc1)'),
    (['foobar', '!=', '1.0.preview'], '(foobar < 1~rc0 or foobar > 1~rc0)'),
    (['foobar', '!=', '1.0-preview1'], '(foobar < 1~rc1 or foobar > 1~rc1)'),
    (['foobar', '!=', '1.0-preview'], '(foobar < 1~rc0 or foobar > 1~rc0)'),
    (['foobar', '!=', '1.0_preview1'], '(foobar < 1~rc1 or foobar > 1~rc1)'),
    (['foobar', '!=', '1.0_preview'], '(foobar < 1~rc0 or foobar > 1~rc0)'),
    (['foobar', '!=', '1.0post1'], '(foobar < 1^post1 or foobar > 1^post1)'),
    (['foobar', '!=', '1.0post'], '(foobar < 1^post0 or foobar > 1^post0)'),
    (['foobar', '!=', '1.0.post1'], '(foobar < 1^post1 or foobar > 1^post1)'),
    (['foobar', '!=', '1.0.post'], '(foobar < 1^post0 or foobar > 1^post0)'),
    (['foobar', '!=', '1.0-post1'], '(foobar < 1^post1 or foobar > 1^post1)'),
    (['foobar', '!=', '1.0-post'], '(foobar < 1^post0 or foobar > 1^post0)'),
    (['foobar', '!=', '1.0_post1'], '(foobar < 1^post1 or foobar > 1^post1)'),
    (['foobar', '!=', '1.0_post'], '(foobar < 1^post0 or foobar > 1^post0)'),
    (['foobar', '!=', '1.0rev1'], '(foobar < 1^post1 or foobar > 1^post1)'),
    (['foobar', '!=', '1.0rev'], '(foobar < 1^post0 or foobar > 1^post0)'),
    (['foobar', '!=', '1.0.rev1'], '(foobar < 1^post1 or foobar > 1^post1)'),
    (['foobar', '!=', '1.0.rev'], '(foobar < 1^post0 or foobar > 1^post0)'),
    (['foobar', '!=', '1.0-rev1'], '(foobar < 1^post1 or foobar > 1^post1)'),
    (['foobar', '!=', '1.0-rev'], '(foobar < 1^post0 or foobar > 1^post0)'),
    (['foobar', '!=', '1.0_rev1'], '(foobar < 1^post1 or foobar > 1^post1)'),
    (['foobar', '!=', '1.0_rev'], '(foobar < 1^post0 or foobar > 1^post0)'),
    (['foobar', '!=', '1.0r1'], '(foobar < 1^post1 or foobar > 1^post1)'),
    (['foobar', '!=', '1.0r'], '(foobar < 1^post0 or foobar > 1^post0)'),
    (['foobar', '!=', '1.0.r1'], '(foobar < 1^post1 or foobar > 1^post1)'),
    (['foobar', '!=', '1.0.r'], '(foobar < 1^post0 or foobar > 1^post0)'),
    (['foobar', '!=', '1.0-r1'], '(foobar < 1^post1 or foobar > 1^post1)'),
    (['foobar', '!=', '1.0-r'], '(foobar < 1^post0 or foobar > 1^post0)'),
    (['foobar', '!=', '1.0_r1'], '(foobar < 1^post1 or foobar > 1^post1)'),
    (['foobar', '!=', '1.0_r'], '(foobar < 1^post0 or foobar > 1^post0)'),
    (['foobar', '!=', '1.0-1'], '(foobar < 1^post1 or foobar > 1^post1)'),
    (['foobar', '<=', '1.0.a1'], 'foobar <= 1~a1'),
    (['foobar', '<=', '1.0.a'], 'foobar <= 1~a0'),
    (['foobar', '<=', '1.0-a1'], 'foobar <= 1~a1'),
    (['foobar', '<=', '1.0-a'], 'foobar <= 1~a0'),
    (['foobar', '<=', '1.0_a1'], 'foobar <= 1~a1'),
    (['foobar', '<=', '1.0_a'], 'foobar <= 1~a0'),
    (['foobar', '<=', '1.0.b1'], 'foobar <= 1~b1'),
    (['foobar', '<=', '1.0.b'], 'foobar <= 1~b0'),
    (['foobar', '<=', '1.0-b1'], 'foobar <= 1~b1'),
    (['foobar', '<=', '1.0-b'], 'foobar <= 1~b0'),
    (['foobar', '<=', '1.0_b1'], 'foobar <= 1~b1'),
    (['foobar', '<=', '1.0_b'], 'foobar <= 1~b0'),
    (['foobar', '<=', '1.0.rc1'], 'foobar <= 1~rc1'),
    (['foobar', '<=', '1.0.rc'], 'foobar <= 1~rc0'),
    (['foobar', '<=', '1.0-rc1'], 'foobar <= 1~rc1'),
    (['foobar', '<=', '1.0-rc'], 'foobar <= 1~rc0'),
    (['foobar', '<=', '1.0_rc1'], 'foobar <= 1~rc1'),
    (['foobar', '<=', '1.0_rc'], 'foobar <= 1~rc0'),
    (['foobar', '<=', '1.0.alpha1'], 'foobar <= 1~a1'),
    (['foobar', '<=', '1.0.alpha'], 'foobar <= 1~a0'),
    (['foobar', '<=', '1.0-alpha1'], 'foobar <= 1~a1'),
    (['foobar', '<=', '1.0-alpha'], 'foobar <= 1~a0'),
    (['foobar', '<=', '1.0_alpha1'], 'foobar <= 1~a1'),
    (['foobar', '<=', '1.0_alpha'], 'foobar <= 1~a0'),
    (['foobar', '<=', '1.0.beta1'], 'foobar <= 1~b1'),
    (['foobar', '<=', '1.0.beta'], 'foobar <= 1~b0'),
    (['foobar', '<=', '1.0-beta1'], 'foobar <= 1~b1'),
    (['foobar', '<=', '1.0-beta'], 'foobar <= 1~b0'),
    (['foobar', '<=', '1.0_beta1'], 'foobar <= 1~b1'),
    (['foobar', '<=', '1.0_beta'], 'foobar <= 1~b0'),
    (['foobar', '<=', '1.0.c1'], 'foobar <= 1~rc1'),
    (['foobar', '<=', '1.0.c'], 'foobar <= 1~rc0'),
    (['foobar', '<=', '1.0-c1'], 'foobar <= 1~rc1'),
    (['foobar', '<=', '1.0-c'], 'foobar <= 1~rc0'),
    (['foobar', '<=', '1.0_c1'], 'foobar <= 1~rc1'),
    (['foobar', '<=', '1.0_c'], 'foobar <= 1~rc0'),
    (['foobar', '<=', '1.0.pre1'], 'foobar <= 1~rc1'),
    (['foobar', '<=', '1.0.pre'], 'foobar <= 1~rc0'),
    (['foobar', '<=', '1.0-pre1'], 'foobar <= 1~rc1'),
    (['foobar', '<=', '1.0-pre'], 'foobar <= 1~rc0'),
    (['foobar', '<=', '1.0_pre1'], 'foobar <= 1~rc1'),
    (['foobar', '<=', '1.0_pre'], 'foobar <= 1~rc0'),
    (['foobar', '<=', '1.0.preview1'], 'foobar <= 1~rc1'),
    (['foobar', '<=', '1.0.preview'], 'foobar <= 1~rc0'),
    (['foobar', '<=', '1.0-preview1'], 'foobar <= 1~rc1'),
    (['foobar', '<=', '1.0-preview'], 'foobar <= 1~rc0'),
    (['foobar', '<=', '1.0_preview1'], 'foobar <= 1~rc1'),
    (['foobar', '<=', '1.0_preview'], 'foobar <= 1~rc0'),
    (['foobar', '<=', '1.0post1'], 'foobar <= 1^post1'),
    (['foobar', '<=', '1.0post'], 'foobar <= 1^post0'),
    (['foobar', '<=', '1.0.post1'], 'foobar <= 1^post1'),
    (['foobar', '<=', '1.0.post'], 'foobar <= 1^post0'),
    (['foobar', '<=', '1.0-post1'], 'foobar <= 1^post1'),
    (['foobar', '<=', '1.0-post'], 'foobar <= 1^post0'),
    (['foobar', '<=', '1.0_post1'], 'foobar <= 1^post1'),
    (['foobar', '<=', '1.0_post'], 'foobar <= 1^post0'),
    (['foobar', '<=', '1.0rev1'], 'foobar <= 1^post1'),
    (['foobar', '<=', '1.0rev'], 'foobar <= 1^post0'),
    (['foobar', '<=', '1.0.rev1'], 'foobar <= 1^post1'),
    (['foobar', '<=', '1.0.rev'], 'foobar <= 1^post0'),
    (['foobar', '<=', '1.0-rev1'], 'foobar <= 1^post1'),
    (['foobar', '<=', '1.0-rev'], 'foobar <= 1^post0'),
    (['foobar', '<=', '1.0_rev1'], 'foobar <= 1^post1'),
    (['foobar', '<=', '1.0_rev'], 'foobar <= 1^post0'),
    (['foobar', '<=', '1.0r1'], 'foobar <= 1^post1'),
    (['foobar', '<=', '1.0r'], 'foobar <= 1^post0'),
    (['foobar', '<=', '1.0.r1'], 'foobar <= 1^post1'),
    (['foobar', '<=', '1.0.r'], 'foobar <= 1^post0'),
    (['foobar', '<=', '1.0-r1'], 'foobar <= 1^post1'),
    (['foobar', '<=', '1.0-r'], 'foobar <= 1^post0'),
    (['foobar', '<=', '1.0_r1'], 'foobar <= 1^post1'),
    (['foobar', '<=', '1.0_r'], 'foobar <= 1^post0'),
    (['foobar', '<=', '1.0-1'], 'foobar <= 1^post1'),
    (['foobar', '<', '1.0.a1'], 'foobar < 1~a1'),
    (['foobar', '<', '1.0.a'], 'foobar < 1~a0'),
    (['foobar', '<', '1.0-a1'], 'foobar < 1~a1'),
    (['foobar', '<', '1.0-a'], 'foobar < 1~a0'),
    (['foobar', '<', '1.0_a1'], 'foobar < 1~a1'),
    (['foobar', '<', '1.0_a'], 'foobar < 1~a0'),
    (['foobar', '<', '1.0.b1'], 'foobar < 1~b1'),
    (['foobar', '<', '1.0.b'], 'foobar < 1~b0'),
    (['foobar', '<', '1.0-b1'], 'foobar < 1~b1'),
    (['foobar', '<', '1.0-b'], 'foobar < 1~b0'),
    (['foobar', '<', '1.0_b1'], 'foobar < 1~b1'),
    (['foobar', '<', '1.0_b'], 'foobar < 1~b0'),
    (['foobar', '<', '1.0.rc1'], 'foobar < 1~rc1'),
    (['foobar', '<', '1.0.rc'], 'foobar < 1~rc0'),
    (['foobar', '<', '1.0-rc1'], 'foobar < 1~rc1'),
    (['foobar', '<', '1.0-rc'], 'foobar < 1~rc0'),
    (['foobar', '<', '1.0_rc1'], 'foobar < 1~rc1'),
    (['foobar', '<', '1.0_rc'], 'foobar < 1~rc0'),
    (['foobar', '<', '1.0.alpha1'], 'foobar < 1~a1'),
    (['foobar', '<', '1.0.alpha'], 'foobar < 1~a0'),
    (['foobar', '<', '1.0-alpha1'], 'foobar < 1~a1'),
    (['foobar', '<', '1.0-alpha'], 'foobar < 1~a0'),
    (['foobar', '<', '1.0_alpha1'], 'foobar < 1~a1'),
    (['foobar', '<', '1.0_alpha'], 'foobar < 1~a0'),
    (['foobar', '<', '1.0.beta1'], 'foobar < 1~b1'),
    (['foobar', '<', '1.0.beta'], 'foobar < 1~b0'),
    (['foobar', '<', '1.0-beta1'], 'foobar < 1~b1'),
    (['foobar', '<', '1.0-beta'], 'foobar < 1~b0'),
    (['foobar', '<', '1.0_beta1'], 'foobar < 1~b1'),
    (['foobar', '<', '1.0_beta'], 'foobar < 1~b0'),
    (['foobar', '<', '1.0.c1'], 'foobar < 1~rc1'),
    (['foobar', '<', '1.0.c'], 'foobar < 1~rc0'),
    (['foobar', '<', '1.0-c1'], 'foobar < 1~rc1'),
    (['foobar', '<', '1.0-c'], 'foobar < 1~rc0'),
    (['foobar', '<', '1.0_c1'], 'foobar < 1~rc1'),
    (['foobar', '<', '1.0_c'], 'foobar < 1~rc0'),
    (['foobar', '<', '1.0.pre1'], 'foobar < 1~rc1'),
    (['foobar', '<', '1.0.pre'], 'foobar < 1~rc0'),
    (['foobar', '<', '1.0-pre1'], 'foobar < 1~rc1'),
    (['foobar', '<', '1.0-pre'], 'foobar < 1~rc0'),
    (['foobar', '<', '1.0_pre1'], 'foobar < 1~rc1'),
    (['foobar', '<', '1.0_pre'], 'foobar < 1~rc0'),
    (['foobar', '<', '1.0.preview1'], 'foobar < 1~rc1'),
    (['foobar', '<', '1.0.preview'], 'foobar < 1~rc0'),
    (['foobar', '<', '1.0-preview1'], 'foobar < 1~rc1'),
    (['foobar', '<', '1.0-preview'], 'foobar < 1~rc0'),
    (['foobar', '<', '1.0_preview1'], 'foobar < 1~rc1'),
    (['foobar', '<', '1.0_preview'], 'foobar < 1~rc0'),
    (['foobar', '<', '1.0post1'], 'foobar < 1^post1'),
    (['foobar', '<', '1.0post'], 'foobar < 1^post0'),
    (['foobar', '<', '1.0.post1'], 'foobar < 1^post1'),
    (['foobar', '<', '1.0.post'], 'foobar < 1^post0'),
    (['foobar', '<', '1.0-post1'], 'foobar < 1^post1'),
    (['foobar', '<', '1.0-post'], 'foobar < 1^post0'),
    (['foobar', '<', '1.0_post1'], 'foobar < 1^post1'),
    (['foobar', '<', '1.0_post'], 'foobar < 1^post0'),
    (['foobar', '<', '1.0rev1'], 'foobar < 1^post1'),
    (['foobar', '<', '1.0rev'], 'foobar < 1^post0'),
    (['foobar', '<', '1.0.rev1'], 'foobar < 1^post1'),
    (['foobar', '<', '1.0.rev'], 'foobar < 1^post0'),
    (['foobar', '<', '1.0-rev1'], 'foobar < 1^post1'),
    (['foobar', '<', '1.0-rev'], 'foobar < 1^post0'),
    (['foobar', '<', '1.0_rev1'], 'foobar < 1^post1'),
    (['foobar', '<', '1.0_rev'], 'foobar < 1^post0'),
    (['foobar', '<', '1.0r1'], 'foobar < 1^post1'),
    (['foobar', '<', '1.0r'], 'foobar < 1^post0'),
    (['foobar', '<', '1.0.r1'], 'foobar < 1^post1'),
    (['foobar', '<', '1.0.r'], 'foobar < 1^post0'),
    (['foobar', '<', '1.0-r1'], 'foobar < 1^post1'),
    (['foobar', '<', '1.0-r'], 'foobar < 1^post0'),
    (['foobar', '<', '1.0_r1'], 'foobar < 1^post1'),
    (['foobar', '<', '1.0_r'], 'foobar < 1^post0'),
    (['foobar', '<', '1.0-1'], 'foobar < 1^post1'),
    (['foobar', '>=', '1.0.a1'], 'foobar >= 1~a1'),
    (['foobar', '>=', '1.0.a'], 'foobar >= 1~a0'),
    (['foobar', '>=', '1.0-a1'], 'foobar >= 1~a1'),
    (['foobar', '>=', '1.0-a'], 'foobar >= 1~a0'),
    (['foobar', '>=', '1.0_a1'], 'foobar >= 1~a1'),
    (['foobar', '>=', '1.0_a'], 'foobar >= 1~a0'),
    (['foobar', '>=', '1.0.b1'], 'foobar >= 1~b1'),
    (['foobar', '>=', '1.0.b'], 'foobar >= 1~b0'),
    (['foobar', '>=', '1.0-b1'], 'foobar >= 1~b1'),
    (['foobar', '>=', '1.0-b'], 'foobar >= 1~b0'),
    (['foobar', '>=', '1.0_b1'], 'foobar >= 1~b1'),
    (['foobar', '>=', '1.0_b'], 'foobar >= 1~b0'),
    (['foobar', '>=', '1.0.rc1'], 'foobar >= 1~rc1'),
    (['foobar', '>=', '1.0.rc'], 'foobar >= 1~rc0'),
    (['foobar', '>=', '1.0-rc1'], 'foobar >= 1~rc1'),
    (['foobar', '>=', '1.0-rc'], 'foobar >= 1~rc0'),
    (['foobar', '>=', '1.0_rc1'], 'foobar >= 1~rc1'),
    (['foobar', '>=', '1.0_rc'], 'foobar >= 1~rc0'),
    (['foobar', '>=', '1.0.alpha1'], 'foobar >= 1~a1'),
    (['foobar', '>=', '1.0.alpha'], 'foobar >= 1~a0'),
    (['foobar', '>=', '1.0-alpha1'], 'foobar >= 1~a1'),
    (['foobar', '>=', '1.0-alpha'], 'foobar >= 1~a0'),
    (['foobar', '>=', '1.0_alpha1'], 'foobar >= 1~a1'),
    (['foobar', '>=', '1.0_alpha'], 'foobar >= 1~a0'),
    (['foobar', '>=', '1.0.beta1'], 'foobar >= 1~b1'),
    (['foobar', '>=', '1.0.beta'], 'foobar >= 1~b0'),
    (['foobar', '>=', '1.0-beta1'], 'foobar >= 1~b1'),
    (['foobar', '>=', '1.0-beta'], 'foobar >= 1~b0'),
    (['foobar', '>=', '1.0_beta1'], 'foobar >= 1~b1'),
    (['foobar', '>=', '1.0_beta'], 'foobar >= 1~b0'),
    (['foobar', '>=', '1.0.c1'], 'foobar >= 1~rc1'),
    (['foobar', '>=', '1.0.c'], 'foobar >= 1~rc0'),
    (['foobar', '>=', '1.0-c1'], 'foobar >= 1~rc1'),
    (['foobar', '>=', '1.0-c'], 'foobar >= 1~rc0'),
    (['foobar', '>=', '1.0_c1'], 'foobar >= 1~rc1'),
    (['foobar', '>=', '1.0_c'], 'foobar >= 1~rc0'),
    (['foobar', '>=', '1.0.pre1'], 'foobar >= 1~rc1'),
    (['foobar', '>=', '1.0.pre'], 'foobar >= 1~rc0'),
    (['foobar', '>=', '1.0-pre1'], 'foobar >= 1~rc1'),
    (['foobar', '>=', '1.0-pre'], 'foobar >= 1~rc0'),
    (['foobar', '>=', '1.0_pre1'], 'foobar >= 1~rc1'),
    (['foobar', '>=', '1.0_pre'], 'foobar >= 1~rc0'),
    (['foobar', '>=', '1.0.preview1'], 'foobar >= 1~rc1'),
    (['foobar', '>=', '1.0.preview'], 'foobar >= 1~rc0'),
    (['foobar', '>=', '1.0-preview1'], 'foobar >= 1~rc1'),
    (['foobar', '>=', '1.0-preview'], 'foobar >= 1~rc0'),
    (['foobar', '>=', '1.0_preview1'], 'foobar >= 1~rc1'),
    (['foobar', '>=', '1.0_preview'], 'foobar >= 1~rc0'),
    (['foobar', '>=', '1.0post1'], 'foobar >= 1^post1'),
    (['foobar', '>=', '1.0post'], 'foobar >= 1^post0'),
    (['foobar', '>=', '1.0.post1'], 'foobar >= 1^post1'),
    (['foobar', '>=', '1.0.post'], 'foobar >= 1^post0'),
    (['foobar', '>=', '1.0-post1'], 'foobar >= 1^post1'),
    (['foobar', '>=', '1.0-post'], 'foobar >= 1^post0'),
    (['foobar', '>=', '1.0_post1'], 'foobar >= 1^post1'),
    (['foobar', '>=', '1.0_post'], 'foobar >= 1^post0'),
    (['foobar', '>=', '1.0rev1'], 'foobar >= 1^post1'),
    (['foobar', '>=', '1.0rev'], 'foobar >= 1^post0'),
    (['foobar', '>=', '1.0.rev1'], 'foobar >= 1^post1'),
    (['foobar', '>=', '1.0.rev'], 'foobar >= 1^post0'),
    (['foobar', '>=', '1.0-rev1'], 'foobar >= 1^post1'),
    (['foobar', '>=', '1.0-rev'], 'foobar >= 1^post0'),
    (['foobar', '>=', '1.0_rev1'], 'foobar >= 1^post1'),
    (['foobar', '>=', '1.0_rev'], 'foobar >= 1^post0'),
    (['foobar', '>=', '1.0r1'], 'foobar >= 1^post1'),
    (['foobar', '>=', '1.0r'], 'foobar >= 1^post0'),
    (['foobar', '>=', '1.0.r1'], 'foobar >= 1^post1'),
    (['foobar', '>=', '1.0.r'], 'foobar >= 1^post0'),
    (['foobar', '>=', '1.0-r1'], 'foobar >= 1^post1'),
    (['foobar', '>=', '1.0-r'], 'foobar >= 1^post0'),
    (['foobar', '>=', '1.0_r1'], 'foobar >= 1^post1'),
    (['foobar', '>=', '1.0_r'], 'foobar >= 1^post0'),
    (['foobar', '>=', '1.0-1'], 'foobar >= 1^post1'),
    (['foobar', '>', '1.0.a1'], 'foobar > 1~a1'),
    (['foobar', '>', '1.0.a'], 'foobar > 1~a0'),
    (['foobar', '>', '1.0-a1'], 'foobar > 1~a1'),
    (['foobar', '>', '1.0-a'], 'foobar > 1~a0'),
    (['foobar', '>', '1.0_a1'], 'foobar > 1~a1'),
    (['foobar', '>', '1.0_a'], 'foobar > 1~a0'),
    (['foobar', '>', '1.0.b1'], 'foobar > 1~b1'),
    (['foobar', '>', '1.0.b'], 'foobar > 1~b0'),
    (['foobar', '>', '1.0-b1'], 'foobar > 1~b1'),
    (['foobar', '>', '1.0-b'], 'foobar > 1~b0'),
    (['foobar', '>', '1.0_b1'], 'foobar > 1~b1'),
    (['foobar', '>', '1.0_b'], 'foobar > 1~b0'),
    (['foobar', '>', '1.0.rc1'], 'foobar > 1~rc1'),
    (['foobar', '>', '1.0.rc'], 'foobar > 1~rc0'),
    (['foobar', '>', '1.0-rc1'], 'foobar > 1~rc1'),
    (['foobar', '>', '1.0-rc'], 'foobar > 1~rc0'),
    (['foobar', '>', '1.0_rc1'], 'foobar > 1~rc1'),
    (['foobar', '>', '1.0_rc'], 'foobar > 1~rc0'),
    (['foobar', '>', '1.0.alpha1'], 'foobar > 1~a1'),
    (['foobar', '>', '1.0.alpha'], 'foobar > 1~a0'),
    (['foobar', '>', '1.0-alpha1'], 'foobar > 1~a1'),
    (['foobar', '>', '1.0-alpha'], 'foobar > 1~a0'),
    (['foobar', '>', '1.0_alpha1'], 'foobar > 1~a1'),
    (['foobar', '>', '1.0_alpha'], 'foobar > 1~a0'),
    (['foobar', '>', '1.0.beta1'], 'foobar > 1~b1'),
    (['foobar', '>', '1.0.beta'], 'foobar > 1~b0'),
    (['foobar', '>', '1.0-beta1'], 'foobar > 1~b1'),
    (['foobar', '>', '1.0-beta'], 'foobar > 1~b0'),
    (['foobar', '>', '1.0_beta1'], 'foobar > 1~b1'),
    (['foobar', '>', '1.0_beta'], 'foobar > 1~b0'),
    (['foobar', '>', '1.0.c1'], 'foobar > 1~rc1'),
    (['foobar', '>', '1.0.c'], 'foobar > 1~rc0'),
    (['foobar', '>', '1.0-c1'], 'foobar > 1~rc1'),
    (['foobar', '>', '1.0-c'], 'foobar > 1~rc0'),
    (['foobar', '>', '1.0_c1'], 'foobar > 1~rc1'),
    (['foobar', '>', '1.0_c'], 'foobar > 1~rc0'),
    (['foobar', '>', '1.0.pre1'], 'foobar > 1~rc1'),
    (['foobar', '>', '1.0.pre'], 'foobar > 1~rc0'),
    (['foobar', '>', '1.0-pre1'], 'foobar > 1~rc1'),
    (['foobar', '>', '1.0-pre'], 'foobar > 1~rc0'),
    (['foobar', '>', '1.0_pre1'], 'foobar > 1~rc1'),
    (['foobar', '>', '1.0_pre'], 'foobar > 1~rc0'),
    (['foobar', '>', '1.0.preview1'], 'foobar > 1~rc1'),
    (['foobar', '>', '1.0.preview'], 'foobar > 1~rc0'),
    (['foobar', '>', '1.0-preview1'], 'foobar > 1~rc1'),
    (['foobar', '>', '1.0-preview'], 'foobar > 1~rc0'),
    (['foobar', '>', '1.0_preview1'], 'foobar > 1~rc1'),
    (['foobar', '>', '1.0_preview'], 'foobar > 1~rc0'),
    (['foobar', '>', '1.0post1'], 'foobar > 1^post1'),
    (['foobar', '>', '1.0post'], 'foobar > 1^post0'),
    (['foobar', '>', '1.0.post1'], 'foobar > 1^post1'),
    (['foobar', '>', '1.0.post'], 'foobar > 1^post0'),
    (['foobar', '>', '1.0-post1'], 'foobar > 1^post1'),
    (['foobar', '>', '1.0-post'], 'foobar > 1^post0'),
    (['foobar', '>', '1.0_post1'], 'foobar > 1^post1'),
    (['foobar', '>', '1.0_post'], 'foobar > 1^post0'),
    (['foobar', '>', '1.0rev1'], 'foobar > 1^post1'),
    (['foobar', '>', '1.0rev'], 'foobar > 1^post0'),
    (['foobar', '>', '1.0.rev1'], 'foobar > 1^post1'),
    (['foobar', '>', '1.0.rev'], 'foobar > 1^post0'),
    (['foobar', '>', '1.0-rev1'], 'foobar > 1^post1'),
    (['foobar', '>', '1.0-rev'], 'foobar > 1^post0'),
    (['foobar', '>', '1.0_rev1'], 'foobar > 1^post1'),
    (['foobar', '>', '1.0_rev'], 'foobar > 1^post0'),
    (['foobar', '>', '1.0r1'], 'foobar > 1^post1'),
    (['foobar', '>', '1.0r'], 'foobar > 1^post0'),
    (['foobar', '>', '1.0.r1'], 'foobar > 1^post1'),
    (['foobar', '>', '1.0.r'], 'foobar > 1^post0'),
    (['foobar', '>', '1.0-r1'], 'foobar > 1^post1'),
    (['foobar', '>', '1.0-r'], 'foobar > 1^post0'),
    (['foobar', '>', '1.0_r1'], 'foobar > 1^post1'),
    (['foobar', '>', '1.0_r'], 'foobar > 1^post0'),
    (['foobar', '>', '1.0-1'], 'foobar > 1^post1'),
])
def test_convert(arg, expected):
    assert convert(*arg) == expected
    assert run_rpmbuild(convert(*arg)) == 0

@pytest.mark.parametrize(('arg', 'expected'), [
    ('pyparsing', 'pyparsing'),
    ('pyparsing>=2.0.1,!=2.0.4,!=2.1.2,!=2.1.6',
     '((pyparsing < 2.0.4 or pyparsing > 2.0.4)'
     ' with (pyparsing < 2.1.2 or pyparsing > 2.1.2)'
     ' with (pyparsing < 2.1.6 or pyparsing > 2.1.6)'
     ' with pyparsing >= 2.0.1)'),
    ('babel>=1.3,!=2.0', '((babel < 2 or babel > 2) with babel >= 1.3)'),
])
def test_convert_requirement(arg, expected):
    assert convert_requirement(arg) == expected
    assert run_rpmbuild(convert_requirement(arg)) == 0
